### ISSUE TITLE
Can't compile if has a custom class whiche inherit from `EditorInspectorPlugin`.

### ISSUE THREAD

**Issue by Daylily-Zeleen** [godotengine/godot-cpp#946]
After [#897](https://github.com/godotengine/godot-cpp/pull/897).

This method:
`virtual bool EditorInspectorPlugin::_parse_property(Object *object, int64_t type, const String &name, int64_t hint_type, const String &hint_string, int64_t usage_flags, bool wide);`
![image](https://user-images.githubusercontent.com/61624558/205448364-84045174-e66f-41ab-b577-5001d54edebe.png)
Can't convert `GDNativeConstObjectPtr` to `GDNativeObjectPtr`.

I try to use `GDNativeObjectPtr` instead of `GDNativeConstObjectPtr` in this template and compiled successfully.

However, It dosen't work and will crash when Godot side try to call my custom `EditorInspectorPlugin::_parse_property()`( follow content are happen before [#897](https://github.com/godotengine/godot-cpp/pull/897), too).
The stack as follow:
![image](https://user-images.githubusercontent.com/61624558/205449404-f377efa7-e7c8-4e31-b947-bccb62a31b9f.png)
I don't know why it will crash with mutex, it is quite weird.

I'm sure this problem is relate on `PtrToArg<Object *>::convert(const void *p_ptr)`
I implement a template specialization for `Object *` as follow:
```
template <>
struct PtrToArg<Object *> {
	_FORCE_INLINE_ static Object *convert(const void *p_ptr) {
		return *(Object **)(p_ptr);
	}
	typedef Object *EncodeT;
	_FORCE_INLINE_ static void encode(Object *p_var, void *p_ptr) {
		*reinterpret_cast<Object **>(p_ptr) = p_var;
	}
};                                                                   
```
It will successfully work with my custom `EditorInspectorPlugin::_parse_property()`, but other functions will become weird.

At last, I try to combine my implement and the template for `Object`, like this:
```
template <class T>
struct PtrToArg<T *> {
	_FORCE_INLINE_ static T *convert(const void *p_ptr) {
		auto ptr = (Object **)(p_ptr);
		if(auto obj = Object::cast_to(*ptr)){
			return obj;
		}
		return reinterpret_cast<T *>(godot::internal::gdn_interface->object_get_instance_binding(*reinterpret_cast<GDNativeObjectPtr *>(const_cast<void *>(p_ptr)), godot::internal::token, &T::___binding_callbacks));
	}
	typedef Object *EncodeT;
	_FORCE_INLINE_ static void encode(T *p_var, void *p_ptr) {
		*reinterpret_cast<const void **>(p_ptr) = p_var ? p_var->_owner : nullptr;
	}
};
```
However, the variable `ptr` alway be a `nullptr` and execute old behavior( crash with mutex lock).

**Comment by touilleMan** [comment]
thanks for the repport @Daylily-Zeleen, as you say that's very likely a bug introduced by #897 !

Can you provide steps to reproduce the compilation error ? (ideally a branch or a patch to apply to the `test` folder) ? I couldn't reproduce the error by just adding an `EditorInspectorPlugin` subclass to the test project :/ 

> However, It dosen't work and will crash when Godot side try to call my custom EditorInspectorPlugin::_parse_property()( follow content are happen before https://github.com/godotengine/godot-cpp/pull/897, too).

Are you sure about the Godot binary you are using is compatible ? I guess you should be fine  if you use the recently released godot beta7 (i.e. if crash occures it's most likely a but an not an incompatibility)

**Comment by Daylily-Zeleen** [comment]
> 

I'm sure my Godot binary is newest, I pulled and built it just after pulling godot-cpp.

Here is the test project.
[inspector_plugin_test.zip](https://github.com/godotengine/godot-cpp/files/10149028/inspector_plugin_test.zip)

Please modify `SConstruct` manually:
```
env = SConscript("../godot-cpp/SConstruct")
```
Then build it.

The test godot project in `/demo`.


Don't forget to modify the `/demo/bin/inspector_plugin_test.gdextension`.

# To reproduce:
1. Disable and enable the plugin saveral times( this may be another issue), ensure the `Output` panel print "_enable_plugin" without error message.
2. Create new scene and add a `TestClass` node.
3. Add element for the property `test_res_arr` of the `TestClass` , as follow: 
![image](https://user-images.githubusercontent.com/61624558/205504126-bf714897-1cb9-490f-bf10-4821237e9ae2.png)

**Comment by touilleMan** [comment]
Ok I could reproduce the issue ;-)

First there is a fix for the casting issue, see #948 

Now for the runtime issue, this is due to [`EditorInspector::instantiate_property_editor` being called in Godot with nullptr as first argument](https://github.com/godotengine/godot/blob/8912f3e4a7c012443e941f4c6f2342c9913fa330/editor/editor_properties_array_dict.cpp#L355)

Godot-CPP doesn't expect to get a `nullptr` for what should be a pointer on a Object and hence segfault when tryin to call `Object::get_instance_binding` on the `nullptr`

I'm not sure if passing a `nullptr` is something allowed or not there (i.e. if that's a Godot or a Godot-CPP bug), @akien-mga do you know more (or know someone who knows ? 😄 )

**Comment by akien-mga** [comment]
> I'm not sure if passing a `nullptr` is something allowed or not there (i.e. if that's a Godot or a Godot-CPP bug), @akien-mga do you know more (or know someone who knows ? :smile: )

I don't know, it does look weird but there aren't a lot of uses of that method to compare. It's indeed the only one passing `nullptr` - seems like it was added this way by @mrcdk back in 2018: https://github.com/godotengine/godot/pull/24129

Would be worth discussing with @reduz and maybe @groud or @KoBeWi.

**Comment by groud** [comment]
Having a quick look to the code, it seems like this line:
```
prop = EditorInspector::instantiate_property_editor(nullptr, value_type, "", subtype_hint, subtype_hint_string, PROPERTY_USAGE_NONE);
```
could likely be replaced by this one:
```
prop = EditorInspector::instantiate_property_editor(object.ptr(), value_type, prop_name, subtype_hint, subtype_hint_string, PROPERTY_USAGE_NONE);
```
since we call `prop->set_object_and_property(object.ptr(), prop_name);` one line after.

Also, if we consider that `nullptr` is not a valid argument (I guess it might make sense, i don't see why you would need use such a helper without providing an object and a property), then we should probably safeguard the function with an `ERR_FAIL_COND_V(object == nullptr, nullptr)`

**Comment by alessandrofama** [comment]
Tagging https://github.com/godotengine/godot-cpp/issues/886 as it's the same issue.

**Comment by Daylily-Zeleen** [comment]
Still have not conclusion?

**Comment by Daylily-Zeleen** [comment]
Can be fixed by https://github.com/godotengine/godot-cpp/pull/992#issue-1529332902.
