### PR TITLE
[SCons] Fix msvc, linux-clang, add version check.

### LINKED ISSUE #779: Windows binding generation fails.
Platform: Windows 11
Current HEAD: 794dea0dd75ed6e914a5d774d728c2eb670656cc

Issue:
```sh
$ scons target=debug generate_bindings=yes
scons: Reading SConscript files ...
AttributeError: 'NoneType' object has no attribute 'generate':
  File "D:\Work\godot-video-reference\godot-cpp\SConstruct", line 117:
    tool.generate(env)
  File "tools\windows.py", line 25:
    base.generate(env)
```

Investigation:
https://github.com/godotengine/godot-cpp/blob/93f2091185ff4390ca8fc8901ebc68ebc35a218f/tools/windows.py#L19
Returns `None`, even with `msvc` installed and it is a part of `env['TOOLS']` when printed.

`git bisect` shows the issue introduced in 93f2091185ff4390ca8fc8901ebc68ebc35a218f

Temporary Fix:
Reverting commit works.

Terminal used:
Developer Powershell for VS 2019
x64 Native Tools Command Prompt for VS 2019

### PR DESCRIPTION
**Pull request by Faless**
Fixes #779.
Closes #780.

Minimum SCons version is set to 4.0 .

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> I've noticed that Godot `master` actually requires scons 3.0.0, so maybe we should test with that version instead, assuming it's enough for all tools.

IMO it's fine if `godot-cpp` has a higher requirement and it's meant to be used by more C++ savvy developers who can be expected to figure out how to get latest SCons. Godot itself still gets compiled by people on old Ubuntu with old SCons who might not know how to use pip to get latest SCons, etc. Though we might want to update the min required SCons version in Godot `master` anyway eventually to ensure people have recent tools like `compiledb` or `ninja`.

**Comment by akien-mga** [comment]
Thanks!
