### ISSUE TITLE
TypedDictionary 'set_typed' identifier not found error when building after updating from 4.4 to 10.0

### ISSUE THREAD

**Issue by mrtripie** [godotengine/godot-cpp#1942]
### Godot version

v4.6.1.stable.official [14d19694e]

### godot-cpp version

master 713481f

### System information

Windows 10, AMD 1700

### Issue description

After updating, I get this error message when running scons:
```
godot-cpp\include\godot_cpp/variant/typed_dictionary.hpp(217): error C3861: 'set_typed': identifier not found
godot-cpp\include\godot_cpp/variant/typed_dictionary.hpp(217): fatal error C1003: error count exceeds 100; stopping compilation
scons: *** [src\composites\utility_selector_behavior.windows.template_debug.x86_64.obj] Error 2
```

I'm not sure if I did something wrong or if this is a bug.
I updated by deleting the `godot-cpp` folder and placing the 10.0rc `godot-cpp` folder in its place, then swapped to the master one when it wasn't working to see if something fixed it.
I ran `scons` from the `godot-cpp` folder to build it, no error. Then scons from the root folder of the gdextension project to build it, where I get this error.

I also restarted the process to see if that fixed it.

What's weird about this error is the class it seems to have trouble with (UtilitySelectorBehavior) uses only a standard Dictionary and it's giving a TypedDictionary error. I think when I originally programmed it in 4.4 it was giving errors when trying to use TypedDictionary, but worked with a standard Dictionary. I don't think it's doing anything especially unusual with the Dictionaries though.

Only 1 other thing then the godot-cpp folder changed since updating where the project broke. I had an extension-api.json file in the root of the project (in addition to the one in godot-cpp/gdextension) that was now outdated. Asking ChatGPT about what it thought might cause this error led to this file being deleted, which didn't change the error I got, and I think its getting too far in the compilation for that file to be needed. I checked some other GDExtensions to see if they had that file and they didn't, so I'm not sure why I had it.

### Steps to reproduce

Download MRP.
Add godot-cpp folder (I think it was too big to include in the MRP zip and successfully upload)
Run scons on godot-cpp
Run scons on the project

### Minimal reproduction project

I hope just giving the whole gdextension project is okay.

[behavior_processor - update bug.zip](https://github.com/user-attachments/files/25699816/behavior_processor.-.update.bug.zip)
